name: AsyncAPI documentation publishing

on:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      #"standard step" where repo needs to be checked-out first
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: GenerateShipment
        uses: asyncapi/github-action-for-cli@v3.1.2
        with:
          command: generate
          filepath: shipping/asyncapi.yaml
          output: build/shipping
          template: '@asyncapi/html-template'

      - name: Build Offer Service AsyncAPI documentation
        uses: docker://asyncapi/github-action-for-generator:2.1.25
        with:
          template: '@asyncapi/html-template'
          filepath: offering/asyncapi.yaml
          output: build/offering

      - name: Build Product Service AsyncAPI documentation
        uses: docker://asyncapi/github-action-for-generator:2.1.25
        with:
          template: '@asyncapi/html-template'
          filepath: product/asyncapi.yaml
          output: build/product

      - name: Build Order Service AsyncAPI documentation
        uses: docker://asyncapi/github-action-for-generator:2.1.25
        with:
          template: '@asyncapi/html-template'
          filepath: order/asyncapi.yaml
          output: build/order

      - name: Build Payment Service AsyncAPI documentation
        uses: docker://asyncapi/github-action-for-generator:2.1.25
        with:
          template: '@asyncapi/html-template'
          filepath: payment/asyncapi.yaml
          output: build/payment

      - name: Build Shopping Basket Service AsyncAPI documentation
        uses: docker://asyncapi/github-action-for-generator:2.1.25
        with:
          template: '@asyncapi/html-template'
          filepath: shoppingBasket/asyncapi.yaml
          output: build/shopping-basket

      - name: Build Customer Service AsyncAPI documentation
        uses: docker://asyncapi/github-action-for-generator:2.1.25
        with:
          template: '@asyncapi/html-template'
          filepath: customer/asyncapi.yaml
          output: build/customer

      - name: Build Shipping Service AsyncAPI documentation
        uses: docker://asyncapi/github-action-for-generator:2.1.25
        with:
          template: '@asyncapi/html-template'
          filepath: shipping/asyncapi.yaml
          output: build/shipping

      #Using another action that takes generated HTML and pushes it to GH Pages
      - name: Deploy GH page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
