name: AsyncAPI documentation publishing

on:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      #"standard step" where repo needs to be checked-out first
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: GenerateOffering
        uses: asyncapi/github-action-for-cli@v3.1.2
        with:
          command: generate
          parameters: '--use-new-generator --force-write'
          filepath: 'offering/asyncapi.yaml'
          cli_version: '2.7.4'
          template: '@asyncapi/html-template'
          output: 'build/offering'

      - name: GenerateShipment
        uses: asyncapi/github-action-for-cli@v3.1.2
        with:
          command: generate
          parameters: '--use-new-generator --force-write'
          filepath: 'shipping/asyncapi.yaml'
          cli_version: '2.7.4'
          template: '@asyncapi/html-template'
          output: 'build/shipping'
      - name: Deploy GH page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build