name: AsyncAPI documentation publishing

on:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      #"standard step" where repo needs to be checked-out first
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: actions/github-script@v7
        id: pwd
        with:
          script: pwd
          result-encoding: string

      - uses: actions/github-script@v7
        id: ls
        with:
          script: ls
          result-encoding: string

      #Using another action for AsyncAPI for validation
      - name: Validating AsyncAPI document
        uses: WaleedAshraf/asyncapi-github-action@v0.0.3
        with:
          filepath: ../offering/asyncapi.yml

      #In case you do not want to use defaults, you, for example, want to use a different template
      - name: Generating HTML from my AsyncAPI document
        uses: asyncapi/github-action-for-generator@v0.2.0
        with:
          template: '@asyncapi/html-template' #In case of template from npm, because of @ it must be in quotes
          filepath: ../offering/asyncapi.yml
          parameters: baseHref=${{github.repository}} sidebarOrganization=byTags #space separated list of key/values
          output: generated-html

      #Using another action that takes generated HTML and pushes it to GH Pages
      - name: Deploy GH page
        uses: JamesIves/github-pages-deploy-action@3.4.2
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: generated-html
